# Generated by Django 2.2.19 on 2022-10-09 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Csv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='csvs')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Orders_vendor',
            fields=[
                ('order', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Номер заказа')),
                ('month_of_order', models.IntegerField(verbose_name='Месяц')),
                ('year_of_order', models.IntegerField(verbose_name='Год')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='РРЦ вендор')),
                ('shipping_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Отгрузка вендор')),
            ],
        ),
        migrations.CreateModel(
            name='Return_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_of_return', models.IntegerField(verbose_name='Месяц в документах которого маркетплейс учел возврат')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Сумма возврата итого по заказу')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Orders_vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Orders_on_claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_paid_for_return', models.BooleanField(verbose_name='Возврат в претензии')),
                ('date_of_claim', models.DateField(verbose_name='Дата претензии')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Orders_vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Orders_market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price_market', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='РРЦ маркетплейс')),
                ('shipping_price_market', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Отгрузка маркетплейс')),
                ('month_of_order_market', models.IntegerField(verbose_name='Месяц маркетплейс')),
                ('year_of_order_market', models.IntegerField(verbose_name='Год маркетплейс')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Orders_vendor')),
            ],
        ),
    ]
